### ISSUE TITLE
Confirm all derivative generation is working

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#10]
_Originally from the https://github.com/Islandora-Devops/isle-buildkit/README.md_

* Confirm all derivative generation is working and check if additional tools need to be build or custom builds of say `poppler utils` or some other tool, etc are needed 
  * need to test against a variety of inputs for each mimetype as there may be some edge case

* Define all inputs and assign testing
  * @dannylamb & @nigelgbanks could you define what this list is and how to test please? I can then assign accordingly or test myself. Thanks!

**Comment by dannylamb** [comment]
I generally upload one of every type.  Here's a list of model/use combos and the derivatives one would expect:

- Model: Image, Original File: Image (png, jpg, gif, etc...)
    - Service FIle
    - Thumbnail Image
    - FITS file
- Model: Image, Original File: File (tiff)
    - Service FIle
    - Thumbnail Image
    - FITS file
- Model: Digital Document, Original File: Document (pdf)
    - Thumbnail Image
    - FITS file
    - Extracted Text
- Model: Audio, Original File: Audio
    - Service File
    - FITS file
- Model: Video, Original File: Video
    - Service File
    - FITS file
- Model: Page, Original File: File (tiff)
    - Service FIle
    - Thumbnail Image
    - FITS file
    - Extracted Text

**Comment by dannylamb** [comment]
This has been working fine for a while now.  Closing.
