### ISSUE TITLE
Change Dockerfile version

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#101]
```bash
# syntax=docker/dockerfile:experimental
```

Is no longer needed, as version 1.2 has now been accepted.

Requires using Docker engine 20.10.0 or higher https://docs.docker.com/engine/release-notes/#20101

This change should wait for some time as it effectively forces users to use the latest Docker.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/isle-buildkit/commit/bda36c93675b3c3e50ef7b364b996382f0878651
