### ISSUE TITLE
Review timeouts and defaults for services around derivative generation

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#102]
Looks like ngnix for Crayfish is timing out after 60 seconds of execution time, ideally there shouldn't be a timeout for any derivative generation services, though something may end up running forever, we'll pass on the responsibility for termination to the service itself rather than relying on nginx.

https://github.com/Islandora-Devops/isle-buildkit/blob/main/crayfish/rootfs/etc/confd/templates/default.conf.tmpl

https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout (default 60 seconds)

[example log houdini.txt](https://github.com/Islandora-Devops/isle-buildkit/files/5769517/houdini.txt)

**Comment by jasonhildebrand** [comment]
I'm running into what seems to be the same issue, 1 year later to the day.

In the docker logs output I'm seeing repeated calls to houdini:

```
houdini_1     | [2022-01-05 21:41:03] app.INFO: Convert request. [] []
houdini_1     | [2022-01-05 21:41:03] app.DEBUG: X-Islandora-Args: {"args":"-thumbnail 100x100"} []
houdini_1     | [2022-01-05 21:41:03] app.DEBUG: Content Types: [] []
houdini_1     | [2022-01-05 21:41:03] app.DEBUG: Content Type Chosen: {"type":"image/jpeg"} []
houdini_1     | [2022-01-05 21:41:03] app.INFO: Imagemagick Command: {"cmd":"convert - -thumbnail 100x100 jpeg:-"} []
...
```
and about 10 seconds later it repeats (again and again).  After a few minutes of this, alpaca spits out:

```
alpaca_1      | 2022-01-05 21:42:52,863 | ERROR | nnector-houdini] | DefaultErrorHandler              | 56 - org.apache.camel.camel-core - 2.20.4 | Failed delivery for (MessageId: queue_islandora-connector-houdini_ID_94ca62ced546-38129-1641418608853-3_6_-1_1_5 on ExchangeId: ID-bea81bcc2a4e-1641418615223-3-11). Exhausted after delivery attempt: 11 caught: java.net.SocketTimeoutException: Read timed out. Processed by failure processor: FatalFallbackErrorHandler[Channel[Log(ca.islandora.alpaca.connector.derivative.DerivativeConnector)[Error connecting generating derivative with http://houdini:8000/convert: ${exception.message}
```
Searching, I found this:  https://github.com/jhu-idc/iDC-general/issues/418 which led me to this: https://github.com/jhu-idc/idc-isle-dc/pull/260/files which led me to my very own .env file which contained:

```
# If you're experiencing timeouts in Alpaca, consider bumping these values for each connector.
ALPACA_OCR_TIMEOUT=10000
ALPACA_FITS_TIMEOUT=10000
ALPACA_HOUDINI_TIMEOUT=10000
ALPACA_HOMARUS_TIMEOUT=10000
```

Oops, I guess I never read this before.  Or maybe I did initially but didn't understand what it meant until today.  But these defaults are really terrible - far too low for a reasonable starting point.

More unfortunately, bumping them up, sourcing my .env file and restarting containers made no difference.  I still see the repeated calls to houdini every 10 seconds, and the final failure messages from alpaca.

**Comment by jasonhildebrand** [comment]
OK, got this sorted.  It was necessary to run `make docker-compose.yml`, because the environment variables get interpolated when docker-compose.yml is generated, not when `docker-compose up` is executed.  This is an isle-dc gotcha which I'm still getting used to.

I will submit a PR against isle-dc to set higher defaults and also document this issue in the troubleshooting.md file.

**Comment by jasonhildebrand** [comment]
The PR is here: https://github.com/Islandora-Devops/isle-dc/pull/209

It sets the default timeouts to 300 seconds.  I believe that PR resolves this issue in a reasonable way.
