### ISSUE TITLE
Add riprap microservice

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#112]
https://github.com/mjordan/riprap

**Comment by nigelgbanks** [comment]
Step one get it setup as a stand alone service, handling alpaca integration will be a separate issue, likely against the alpaca repo

**Comment by nigelgbanks** [comment]
Reference implementation from roblib: https://github.com/roblib/Islandora-Devops.riprap

**Comment by nikathone** [comment]
@nigelgbanks FYI I did build a docker image a while ago to use it with the Ansible playboook at https://gitlab.com/nikathone/riprap_docker for demonstration purposes. Not sure if you might something to reuse.

**Comment by nigelgbanks** [comment]
@nikathone thanks for letting me know I'll have a read through and see what I can use!

**Comment by nigelgbanks** [comment]
Merged in here: https://github.com/Islandora-Devops/isle-buildkit/pull/113
