### ISSUE TITLE
[MARIADB] Grant permissions for root user not taken into account

### ISSUE THREAD

**Issue by Tristaan** [Islandora-Devops/isle-buildkit#115]
Hello,
When trying to connect to the mysql daemon from the docker network it emits an error:
`ERROR 1045 (28000): Access denied for user 'root'@'isle-dc_drupal_1.isle-dc_default'`
If trying to connect from inside the container it works as expected.
To fix this issue I reran the GRANT command inside the mariadb mysql client.
From then on it works as expected. Looking through the container init, the required [line](https://github.com/Islandora-Devops/isle-buildkit/blob/main/mariadb/rootfs/etc/cont-init.d/03-mysql-setup.sh#L29) is present.
Running grants by hand didn't fix the issue, but what did fix the issue is to also specify a password when doing a GRANT, Like so:
`GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;`

SO I propose combining [lines 27-29](https://github.com/Islandora-Devops/isle-buildkit/blob/main/mariadb/rootfs/etc/cont-init.d/03-mysql-setup.sh#L29) into the aforementioned command.

This was tested against `171f43d75c7c16b07e16dc8eec58a75a8a6e7586` latest

**Comment by nigelgbanks** [comment]
Sounds reasonable to me, do you wanna send up a pull request and I'll test and merge?

**Comment by nigelgbanks** [comment]
Tested and merged.
