### ISSUE TITLE
TLS for etcd?

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#12]
_Originally from the https://github.com/Islandora-Devops/isle-buildkit/README.md_

* Do we need to support tls for etcd? Probably not since it shouldn't be exposed outside of the network. Though would be nice.

**Comment by nigelgbanks** [comment]
Closing this for now as no one is really using etcd, and if we abandon confd for something else we'll probably have to drop support for etcd anyway: https://github.com/Islandora-Devops/isle-buildkit/issues/117
