### ISSUE TITLE
Error while Matomo is initializing

### ISSUE THREAD

**Issue by Tristaan** [Islandora-Devops/isle-buildkit#124]
When running with isle-dc I get an error. The error is:
```
ERROR 1146 (42S02) at line 15: Table 'matomo.matomo_site' doesn't exist
``` 
In the 03-matomo-setup.sh. The table is ALTERed and should be created using `/etc/matomo/create-matomo-database.sql`, but none of the tables are created. So i presume this sql script is not executing.

**Comment by nigelgbanks** [comment]
It won't run if the database already exists. That might be the issue. Might be an upgrade problem.

**Comment by nigelgbanks** [comment]
Hmm that table should have existed for the last 10 months, is this a fresh install?

**Comment by Tristaan** [comment]
Retried fresh. Now it works. Thanks. Please check #125.
