### ISSUE TITLE
Error while running fcrepo6

### ISSUE THREAD

**Issue by Tristaan** [Islandora-Devops/isle-buildkit#125]
When running fcrepo6 after the initialization the services.d, which starts `tomcat/rootfs/etc/services.d/tomcat/run` and this return the java usage options. So there must be something going on with catalina.sh or something wrong with JAVA_OPTS in `fcrepo6/rootfs/opt/tomcat/bin/setenv.sh`. I keep the TOMCAT_JAVA_OPTS unset.

**Comment by nigelgbanks** [comment]
When fcrepo6 starts it will source https://github.com/Islandora-Devops/isle-buildkit/blob/main/fcrepo6/rootfs/opt/tomcat/bin/setenv.sh which sets `JAVA_OPTS` and `CATALINA_OPTS` before starting tomcat. 

Can you paste the error your getting on startup?

**Comment by Tristaan** [comment]
There is no error, just the java usage.
```
fcrepo_1      | [services.d] starting services
fcrepo_1      | [services.d] done.
fcrepo_1      | Usage: java [options] <mainclass> [args...]
fcrepo_1      |            (to execute a class)
...
```

**Comment by nigelgbanks** [comment]
@Tristaan can you check with the most recent changes on isle-dc development branch?

**Comment by Tristaan** [comment]
@nigelgbanks Works.
