### ISSUE TITLE
Mysql permission problems persist

### ISSUE THREAD

**Issue by Tristaan** [Islandora-Devops/isle-buildkit#126]
#116 did not fix the root@% permission problem when using isle-dc. The error is raised again. After running the container set, I need to manually fix mariadb with `GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY ${DB_ROOT_PASSWORD}`.
[L27-29](https://github.com/Islandora-Devops/isle-buildkit/blob/89212b323c1ddf873b7f9c9ebc84a88aebfeee5e/mariadb/rootfs/etc/cont-init.d/03-mysql-setup.sh#L27). So the password should be set with [IDENTIFIED BY](https://mariadb.com/kb/en/grant/#identified-by-password).

**Comment by Tristaan** [comment]
So I have done some testing, and changing the L27-29 has no effect. I always need to set the GRANT manually. I need someone to confirm this.

**Comment by nigelgbanks** [comment]
This is a new bug caused by recent changes.

**Comment by Tristaan** [comment]
Fixed with #127.
