### ISSUE TITLE
Support for S3 bucket prefixes would be GREAT

### ISSUE THREAD

**Issue by noahwsmith** [Islandora-Devops/isle-buildkit#129]
See the last line of https://wiki.lyrasis.org/display/FEDORA6x/Amazon+S3 : if we pass `-Dfcrepo.ocfl.s3.prefix=<some-prefix>` we can actually use a subdir of a Bucket, which is really nice for development purposes, or for allowing programmatic review environments. Is this as simple as adding this here? https://github.com/Islandora-Devops/isle-buildkit/blob/main/fcrepo/rootfs/etc/confd/templates/repository.json.tmpl#L43

**Comment by noahwsmith** [comment]
cc @emudojo

**Comment by nigelgbanks** [comment]
That location is for fcrepo5 only, with fcrepo6 you'd need to do it as part of [setenv.sh](https://github.com/Islandora-Devops/isle-buildkit/blob/main/fcrepo6/rootfs/opt/tomcat/bin/setenv.sh)

**Comment by nigelgbanks** [comment]
Looks to have been implemented by the [pull](https://github.com/Islandora-Devops/isle-buildkit/pull/134)
