### ISSUE TITLE
No shared volumes for easier movement between nodes in a cluster

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#14]
_Originally from the https://github.com/Islandora-Devops/isle-buildkit/README.md_

* Ideally no shared volumes as then containers can be more easily moved between nodes in a cluster

**Comment by nigelgbanks** [comment]
It's down to just Solr now

**Comment by nigelgbanks** [comment]
Closing now since we have a solr specific ticket: https://github.com/Islandora-Devops/isle-buildkit/issues/13
