### ISSUE TITLE
Developer workflow documentation / examples

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#15]
_ Originally from the https://github.com/Islandora-Devops/isle-buildkit/README.md_

* Developer workflow documentation / examples
  * How to build
  * How to edit gradle configurations
  * How to use the continuous build workflow
  * How to develop Drupal 8 using the two types of build workflows (normal and continuous)
  * How to push from a local build to a repository

**Comment by nigelgbanks** [comment]
I think this is largely covered now, as there have been a number of changes.

> How to build

Currently [documented](https://github.com/Islandora-Devops/isle-buildkit#building) in the top level README.

> How to edit gradle configurations

Essentially no Gradle code resides in the repository anymore it's all been moved to a standalone [plugin](https://github.com/Islandora-Devops/isle-gradle-docker-plugin). 

> How to use the continuous build workflow

Documented [here](https://github.com/Islandora-Devops/isle-buildkit#building-continuously)

> How to develop Drupal 8 using the two types of build workflows (normal and continuous)

Development has moved to [isle-dc](https://github.com/Islandora-Devops/isle-dc) and images are pulled from DockerHub so not relevant anymore.

> How to push from a local build to a repository

Currently locked down as only the Github actions have the credentials to push to DockerHub.
