### ISSUE TITLE
Handle .txt files

### ISSUE THREAD

**Issue by kayakr** [Islandora-Devops/isle-buildkit#154]
If I add a Repository Item with Model=Binary, then add an associated Media of type File with a `text/plain` e.g. `test-text-file.txt` the media is created but the default media link to download the file https://islandora.traefik.me/_flysystem/fedora/2021-07/test-text-file.txt generates a 404 via nginx.

If visit the fcrepo record, e.g. http://islandora.traefik.me:8081/fcrepo/rest/2021-07/test-text-file.txt/fcr:metadata, and click 'Download Content' button the file is downloaded ok http://islandora.traefik.me:8081/fcrepo/rest/2021-07/test-text-file.txt

**Comment by nigelgbanks** [comment]
Sounds like either a bug in Islandora or in the configuration of Drupal / Islandora. Moving the ticket to either https://github.com/Islandora/islandora/pulls or https://github.com/Islandora-Devops/isle-dc/issues, will increase the chances of someone tackling it.

**Comment by kayakr** [comment]
@nigelgbanks I just tried this on an existing Drupal using Ansible Playbook and http://islandora8-demo.local:8000/_flysystem/fedora/2021-07/test-text-file.txt serves without error, so it looks like an isle-dc issue, or it's related to the nginx config at https://github.com/Islandora-Devops/isle-buildkit/blob/main/drupal/rootfs/etc/nginx/shared/drupal.defaults.conf

**Comment by nigelgbanks** [comment]
My bad you are right, this is the config responsible: https://github.com/Islandora-Devops/isle-buildkit/blob/main/drupal/rootfs/etc/nginx/shared/drupal.defaults.conf#L21-L24 I thought Danny, had resolved this before, but maybe I've re-introduced it.

**Comment by nigelgbanks** [comment]
Ahh this was Danny's fix: https://github.com/Islandora-Devops/isle-buildkit/blob/main/drupal/rootfs/etc/nginx/shared/drupal.defaults.conf#L15-L18 it only affects those txt files servied from the sites files directory, we also need to account for flystem it would seem.

**Comment by nigelgbanks** [comment]
Odd though I would expect it to be 403 forbidden if nginx was denying the request

**Comment by nigelgbanks** [comment]
Ya seems like the rule:

```conf
# Allow access to .txt files served by flysystem    
location ~ ^/_flysystem/.*\.txt$ {                  
    allow all;                                      
}
```
Does not resolve the issue.

**Comment by nigelgbanks** [comment]
This is very odd seems like flystem isn't fetching the file, and nginx is trying to read from disk.
```bash
drupal_1      | 2021/07/20 08:14:20 [error] 1160#1160: *558 open() "/var/www/drupal/web/_flysystem/fedora/2021-07/test.txt" failed (2: No such file or directory), client: 172.20.0.3, server: drupal, request: "GET /_flysystem/fedora/2021-07/test.txt HTTP/1.1", host: "islandora.traefik.me", referrer: "https://islandora.traefik.me/media/132"
```

**Comment by kayakr** [comment]
@nigelgbanks It has to get past nginx to reach Drupal before flysystem can handle it.
What if you comment out the rule around https://github.com/Islandora-Devops/isle-buildkit/blob/main/drupal/rootfs/etc/nginx/shared/drupal.defaults.conf#L21 ?

**Comment by nigelgbanks** [comment]
It doesn't have any affect in this case, I think this might be some problem with how flysystem is configured or perhaps there is a bug, it might not be the exact same version that is running under Ansible.

**Comment by nigelgbanks** [comment]
I'm attaching a debugger now, hopefully it'll shed some light as to whats going on.

**Comment by nigelgbanks** [comment]
Pff debuggers not working

**Comment by nigelgbanks** [comment]
Bear with me I don't normally use isle-dc, or fedora.

**Comment by kayakr** [comment]
@nigelgbanks FWIW both instances have Flysystem 2.0.0-alpha1 2.0.0-alpha1 but isle-dc/nginx doesn't handle `.txt` whereas ansible/apache does.

**Comment by nigelgbanks** [comment]
I removed the `nginx` rule to no affect, if it was being applied the request would return `403` rather than `404`.  With the other rule I added, serving from disk at the path `_flysystem/fedora/2021-07/` works.

**Comment by kayakr** [comment]
@nigelgbanks AFAICT Ansible apache `/etc/apache2/sites-enabled/islandora.conf` has no restrictions on txt files, e.g. http://islandora8-demo.local:8000/README.txt serves ok (probably shouldn't).

**Comment by kayakr** [comment]
@nigelgbanks how are you restarting nginx to apply the new config?

**Comment by nigelgbanks** [comment]
Oh no it is again my bad, it's the combination of the two rules with the new one I had added.

**Comment by nigelgbanks** [comment]
Ya I'm rebuilding and redeploying

**Comment by nigelgbanks** [comment]
The `404` is cause the rule I added made it attempt to read from disk, rather than allowing the request to go on to `index.php`.

**Comment by nigelgbanks** [comment]
No file on disk means `404`

**Comment by nigelgbanks** [comment]
I've applied a fix and raised a pull request if you want to review it?

https://github.com/Islandora-Devops/isle-buildkit/pull/155

Thanks for finding this issue, and being so responsive and helpful!
