### ISSUE TITLE
Crayfish is out of date

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-buildkit#158]
[Crayfish](https://github.com/Islandora/crayfish) has a 2.0.0 release, and will be using semantic versioning from now on. The code here pulls a stale commit.

https://github.com/Islandora-Devops/isle-buildkit/blob/main/crayfish/Dockerfile

**Comment by nigelgbanks** [comment]
Was resolved by the [pull](https://github.com/Islandora-Devops/isle-buildkit/pull/160)
