### ISSUE TITLE
Introduction is too vague and missing docs on how to get to work with Isle-dc

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Devops/isle-buildkit#162]
The "**Introduction**" should make it clear what this repo does and is intended for. The README says how to spin buildkit up and that it can be "_used to build an Islandora 8 site_" but this is vague. A more refined description is much further down in the rest of the README and could easily be missed. Users shouldn't need to completely read the README to find out at the end that this isn't the repo they're looking for.

* There is no indication to the user that this isn't intended for "trying Islandora". The verbiage should be clear that for spinning up Islandora use isle-dc or the Ansible solution.
* There should be some comment to make it clear this is for advanced users to customize the server environments that run Islandora/Drupal and all of its counterparts. For customization of Islandora/Drupal see Isle-dc.
* There's no information on how to get isle-dc to use isle-buildkit directly. If I run the buildkit, what do I need to modify in Isle-dc to get it to not fetch the public one and start using the local one I just built?

**Comment by nigelgbanks** [comment]
Raised a [pull request](https://github.com/Islandora-Devops/isle-buildkit/pull/164) the first two points. 

For the third its documented inline in the isle-dc repository [here](https://github.com/Islandora-Devops/isle-dc/blob/development/sample.env#L54-L58)

**Comment by rosiel** [comment]
I think @nigelgbanks 's PR  #164 vastly improves the landing-on-buildkit experience, but will defer to @DonRichards  - is this ticket completed?

**Comment by nigelgbanks** [comment]
Closing the issue as @DonRichards has approved the changes on #164
