### ISSUE TITLE
Document the release process for isle in the main ReadMe.

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#169]

**Comment by g7morris** [comment]
Leaving a note here that so far I've identified that: 

* ISLE maintainers make a change / PR 
  * ISLE maintainer should assign a testing resource (either another ISLE maintainer, community member or ISLE Release Manager)
  * PR creates new Docker images tag (TAG) using git commit hash
  * Assigned testing resource can test this by
    * `git clone git@github.com:Islandora-Devops/isle-dc.git`  to local laptop
    * `cd isle-dc`
    * `cp sample.env .env`
    * `vi / nano .env`
    * Change TAG to appropriate git commit hash
    * `make demo`
    * QC site and report back on Github issue if pass / fail
    * Recommend the following for filing tickets / issues. Example below

#### Example for isle-buildkit testing

```bash
Reporting results from testing process:

#### Test Environment

* OS: Ubuntu 20.04 LTS Desktop
* CPU: Intel i7-10510U (8 cores) @ 4.900 GHZ
* Mem: 32 GB

---

#### Test process / steps

When testing isle-buildkit
* `git clone git@github.com:Islandora-Devops/isle-buildkit.git` to local laptop
* `git checkout `/matomo-volume-redux`
* `./gradlew build`

#### Results

Describe output, expectation and steps. 

Include screenshots etc.
```

#### Example for isle-dc testing

```bash
Reporting results from testing process:

#### Test Environment

* OS: Ubuntu 20.04 LTS Desktop
* CPU: Intel i7-10510U (8 cores) @ 4.900 GHZ
* Mem: 32 GB

---

    * `git clone git@github.com:Islandora-Devops/isle-dc.git`  to local laptop
    * `cd isle-dc`
    * `cp sample.env .env`
    * `vi / nano .env`
    * Change TAG to appropriate git commit hash
    * `make demo`
---

#### Results

Describe output, expectation and steps. 

Include screenshots etc.
```

**Comment by g7morris** [comment]
@nigelgbanks Should I just make a .md file to this effect and get the ball rolling for you?

**Comment by nigelgbanks** [comment]
@g7morris ya sure that sounds good if you raise a pull request I'll review and merge it.

**Comment by g7morris** [comment]
@nigelgbanks 1st pass at this. probably missing a few bits and bobs for sure. Please feel free to edit away, I wasn't sure how we would handle release notes so I put in a template? https://github.com/Islandora-Devops/isle-buildkit/pull/199
