### ISSUE TITLE
Get working with Kubernetes with auto scaling for micro-services

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#17]
_Originally from the https://github.com/Islandora-Devops/isle-buildkit/README.md_

* Get working with Kubernetes with auto scaling for micro-services

**Comment by nigelgbanks** [comment]
This ticket is from a time before we split the repo to have a separated isle-dc. The repository is now only responsible for constructing the images not for any orchestration. If we do eventually have a public implementation using ECS/EKS it will live in a different repository and just consume the images produced by this one.
