### ISSUE TITLE
Uploading tiffs fails in Drupal

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#18]
From https://github.com/Islandora-Devops/isle-buildkit/pull/6

@dannylamb reported the following:

**Caveats**

> I can't seem to upload tiffs appropriately. This doesn't have anything to do with cantaloupe as far as I can tell. I can upload it in the widget in Drupal, but after I save the form, a File entity is created but the file itself is not in Fedora. man_shrugging Looks like it's getting stripped out by Traefik or Fedora's nginx proxy. I'll defer to @nigelgbanks on that one.

From @nigelgbanks 
Don't know what the problem is with tiff files, but that's definitely a different pull request / ticket.

**Comment by dannylamb** [comment]
Superseded by https://github.com/Islandora-Devops/isle-buildkit/issues/26
