### ISSUE TITLE
Is the nginx proxy in tomcat still required?

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#186]
In reviewing the [timeouts](https://github.com/Islandora-Devops/isle-buildkit/pull/185), I wondered if the nginx proxy is still required for tomcat? Originally I think it was there for embedded links to Fedora 5 (isle now exposes it on a specific port rather than at it's own domain)? Maybe something to do with gemini or microservices? I can't really remember to be honest.

**Comment by nigelgbanks** [comment]
Ya it's not required derivatives are created, things make it into fedora all seems fine without it.

**Comment by nigelgbanks** [comment]
https://github.com/Islandora-Devops/isle-buildkit/pull/187
https://github.com/Islandora-Devops/isle-dc/pull/222

**Comment by g7morris** [comment]
@nigelgbanks Okay to close this issue if https://github.com/Islandora-Devops/isle-buildkit/pull/187 has been merged?

**Comment by nigelgbanks** [comment]
Yup it can be closed.
