### ISSUE TITLE
Cannot perform isle-buildkit tests on M1 macbook

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#207]
Need to upgrade Gradle when this makes it into the next tagged release: https://github.com/gradle/gradle/commit/9059e16903f9536d37246264902437b645ce0825

**Comment by g7morris** [comment]
From https://gradle.org/releases/ The current Gradle release is  v7.4.2 as of Mar 31, 2022

We're waiting on this to update.

**Comment by nigelgbanks** [comment]
7.5 has been released I'll open up a pull after I test.
