### ISSUE TITLE
gs command error in houdini container (tag tested: alpha-16) causing missing PDF thumbnails

### ISSUE THREAD

**Issue by jefferya** [Islandora-Devops/isle-buildkit#210]
When adding a PDF media, the houdini container is throwing a `gs` error in container images tagged `alpha-16`.  Thumbnail generation for PDFs is failing 

```
[2022-04-20 14:54:13] app.ERROR: Process exited with non-zero code. {"exit_code":1,"stderr":"sh: gs: not found\nconvert: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dPrinted=false '-sOutputFile=/tmp/magick-4uAykMEa3uKG8Ln4pXBBQqz2SzdlHLeL%d' '-f/tmp/magick-aQ3Vo51htJSTdte3RUJKepFPC7ODODHp' '-f/tmp/magick-A5ej0PEelkN9N7sp1CzgNJRptUdbjJAP'' (32512) @ error/ghostscript-private.h/ExecuteGhostscriptCommand/74.\nconvert: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3322.\n"} []
--
Wed, Apr 20 2022 8:54:13 am | [2022-04-20 14:54:13] app.ERROR: RuntimeException: {"exception":"[object] (RuntimeException(code: 500): sh: gs: not found\nconvert: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dPrinted=false '-sOutputFile=/tmp/magick-4uAykMEa3uKG8Ln4pXBBQqz2SzdlHLeL%d' '-f/tmp/magick-aQ3Vo51htJSTdte3RUJKepFPC7ODODHp' '-f/tmp/magick-A5ej0PEelkN9N7sp1CzgNJRptUdbjJAP'' (32512) @ error/ghostscript-private.h/ExecuteGhostscriptCommand/74.\nconvert: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3322.\n at /var/www/crayfish/Houdini/vendor/islandora/crayfish-commons/CmdExecuteService.php:120)"} []
```

If is ` docker-compose exec houdini with-contenv bash` into the container the `gs` command is not found. `apk list -I | grep -i ghost` shows that ghostscript is not installed.

If I try older container images tagged 4f163544d69df6dd1dd2fdca9ad10ba2bcabe8b5, the `gs` command works `/usr/bin/gs`.

To test:
* resource type: text
* model: digital document
* add media: type document
* add PDF

Could the following change be the reason:

https://github.com/Islandora-Devops/isle-buildkit/commit/2ee80c71cc5689a11316610e32b49fe5fc73bc15#diff-2ecbd9b5a5378621657c89629c1a353c2bf1ccf4bd4520766cb9e4d04241731bL16-L19

**Comment by rbos** [comment]
I'm also experiencing this problem. I manually added gs by installing the apk (gave the container network access, "apk add ghostscript"). It still doesn't seem to be generating thumbnails, but it's not generating an error either, but I might be doing it wrong.

**Comment by nigelgbanks** [comment]
@jefferya 100% that's the issue, `ghostscript` was something we added after the fact for `imagemagick` as a dependency. The commit you pointed to the build script for the package was taken from the latest Alpine release at the time so I introduced a regression. I'll test locally and raise a pull request.

**Comment by nigelgbanks** [comment]
I raised a pull request here: https://github.com/Islandora-Devops/isle-buildkit/pull/211

I've tested it locally, once the github action finishes on the pull request others can confirm this to be fixed as well. Once merged I'll mint a new alpha release.

**Comment by nigelgbanks** [comment]
Pull request was approved and merged, closing issue.
