### ISSUE TITLE
Upgrade alpine and remove customisation for JNA in the fits image.

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#215]
The following has been merged in `aports`:

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/34087

Which should fix the issue where we had to have customisation to the [jna](https://github.com/java-native-access/jna) packages for fits to support arm builds. 

After upgrading to `3.15.5` when it releases we should be able to cleanup:

https://github.com/Islandora-Devops/isle-buildkit/blob/c85af8b67b553198cafda35dab7cc7f0e74ecffe/fits/Dockerfile#L60-L78

And remove the custom build: https://github.com/Islandora-Devops/isle-buildkit/tree/main/fits/build.

This will require testing on arm to validate that fits is working properly when calling out to native code.

**Comment by nigelgbanks** [comment]
Need to wait on this getting in to be able to use Drupal 8:

https://github.com/roblib/CrayFits/pull/10

**Comment by g7morris** [comment]
@nigelgbanks Do you want to schedule a Zoom call re this task or talk in Slack sometime this week to divvy up next steps between the two of us?

**Comment by nigelgbanks** [comment]
Linking the existing work here: https://github.com/Islandora-Devops/isle-buildkit/pull/238

**Comment by nigelgbanks** [comment]
@g7morris I'll ping ya on slack.

**Comment by rosiel** [comment]
Discussed briefly in the Tech call today; looks like you have a solid plan for this. let us know if you need more community input.

**Comment by nigelgbanks** [comment]
Even though they added jna back in for aarch64, we can't use it as it's compiled against a newer version of java, so we will have to continue using our own build package.

**Comment by nigelgbanks** [comment]
Upgraded to JDK 17 (The new LTS for JDK) to get around problems with Fcrepo deadlocking when receiving a SIGTERM. Might work now.

**Comment by nigelgbanks** [comment]
Yup that worked.

**Comment by nigelgbanks** [comment]
DOne under https://github.com/Islandora-Devops/isle-buildkit/pull/238
