### ISSUE TITLE
Set Default Log Levels for Containers to Warning or Error?

### ISSUE THREAD

**Issue by misilot** [Islandora-Devops/isle-buildkit#217]
Can the default log levels be set to warning or error, with the option to override them via ENV variables?

`cantaloupe` is outputting at least DEBUG logs
`fits` is outputting at least INFO logs
`activemq` is outputting INFO as well
...

**Comment by nigelgbanks** [comment]
All logging levels should be override-able via the environment variables noted in the images README, or in the case of their parent images README for things that use some services like `nginx` or `tomcat`. The defaults thus far have been what was shipped as defaults from each of the tools we're using. 

That being said choosing one level and using it everywhere sounds reasonable to me. I'd tend to go with `INFO` everywhere in such a case though. It would make it easier for people using the defaults to provide information in their tickets, but still isn't as overwhelming as `DEBUG`.

@g7morris and @jefferya do you want to weigh in with a preference?

**Comment by jefferya** [comment]
I think the default level should be targeted to a specific use-case. I see `ERROR`/`WARN` defaults targeting a production or user who doesn't want/need logs. Or `INFO`/`DEBUG` targeting testers/developers trying to troubleshoot.  `INFO` everywhere for the reason Nigel mentions has merit in my opinion however, I don't have a strong opinion.

**Comment by g7morris** [comment]
Late to the party. The ability to change the levels via confd or variables is the key feature here. 

With respect to preferences, I'm with @nigelgbanks  `INFO` should always be default as a rote level of debugging is typically needed though I also agree with @misilot on Prod system needs being more conservative and less verbose so see point #1 above ;)

**Comment by g7morris** [comment]
Okay the following services have been bumped up one level from `debug` to a less talkative `info`

* crayfits
* homarus
* houdini
* hypercube
* milliner
* recast
* riprap

All other services were set to the following `notice, error or warn` which in our opinion were sufficient or optimal given their function e.g. `confd` or `php` errors aren't typically read

**Comment by nigelgbanks** [comment]
This has been rolled out in release 1.0.7
