### ISSUE TITLE
Upgrade to FITS 1.5.5

### ISSUE THREAD

**Issue by misilot** [Islandora-Devops/isle-buildkit#218]
From https://github.com/Islandora-Devops/isle-buildkit/pull/208 it mentions to upgrade to the latest FITS version once the fix was released.

1.5.3 was released which includes the fix that was addressed.

https://github.com/harvard-lts/fits/issues/316#issuecomment-1115017149

**Comment by g7morris** [comment]
@nigelgbanks https://github.com/Islandora-Devops/isle-buildkit/pull/234

**Comment by nigelgbanks** [comment]
This got rolled out in the 1.0.7 release
