### ISSUE TITLE
Update Fedora 6 to newer release

### ISSUE THREAD

**Issue by misilot** [Islandora-Devops/isle-buildkit#219]
6.1.0 adds support for building on M1 (ARM). 

I also see logs about using MariaDB 10.6 instead of 10.5, but I don't think it's been updated to support a newer db version.

```
fcrepo_1      | WARN 19:22:47.639 [main] (Database) Flyway upgrade recommended: MariaDB 10.6 is newer than this version of Flyway and support has not been tested. The latest supported version of MariaDB is 10.5.`
```

Release notes 

https://github.com/fcrepo/fcrepo/releases/tag/fcrepo-6.1.0
https://github.com/fcrepo/fcrepo/releases/tag/fcrepo-6.1.1

**Comment by nigelgbanks** [comment]
We don't build `fcrepo6` in this repository, we just consume the `war` they release which is cross platform. So we do not need the M1 support added in [FCREPO-3734](https://fedora-repository.atlassian.net/browse/FCREPO-3734). Updating is a good idea though regardless.

**Comment by noahwsmith** [comment]
Pushed #233

**Comment by noahwsmith** [comment]
Our tests show that this container works well, and no extra fedora upgrade steps were needed from 6.0.0 to 6.2.0
