### ISSUE TITLE
RECAST_DRUPAL_URL and RECAST_FCREPO_URL values

### ISSUE THREAD

**Issue by misilot** [Islandora-Devops/isle-buildkit#220]
https://github.com/Islandora-Devops/isle-buildkit/blob/main/recast/Dockerfile#L15-L16

Should these values be? 

`RECAST_DRUPAL_URL=http://drupal:80`
`RECAST_FCREPO_URL=http://fcrepo:8080/fcrepo/rest`

**Comment by nigelgbanks** [comment]
Not 100% sure things that communicate back with islandora are a bit weird in that they require the external `url`, for some aspects to work. I've not been using `fedora` in most of the setups I have. @dannylamb do you want to weight in?

**Comment by dannylamb** [comment]
I think you want those to be the real domain of the site, since that'll be what gets slapped into the fedora document when you view it through the recast service.

It's been a hot minute since I last used that service though.  I pulled it out of deployments for BD just to keep things leaner. 
 @misilot are you trying to use recast and running into problems?

**Comment by misilot** [comment]
@dannylamb no, and I'll be honest I have no clue what recast is ...

I am seeing errors in alpaca and milliner in the logs, so it had me start going through things, and looking at the different environments trying to figure out what might be wrong and saw that set as islandora.traefik.me ...., and with the change of the fedora port from 80 to 8080 made me start digging more in case it was that ...

**Comment by g7morris** [comment]
@dannylamb & @nigelgbanks Is this still an issue to pursue?

**Comment by g7morris** [comment]
I would argue we don't want to be hardcoding ANY domain at all here but rather use a variable from the .env file e.g. DOMAIN=

or we should copy what other services do here e.g. milliner https://github.com/Islandora-Devops/isle-buildkit/blob/main/milliner/Dockerfile#L16 seems to use the fcrepo service `MILLINER_FCREPO_URL=http://fcrepo:8080/fcrepo/rest \`

**Comment by g7morris** [comment]
@nigelgbanks Do you want to schedule a Zoom call re this task or talk in Slack sometime this week to divvy up next steps between the two of us?

**Comment by nigelgbanks** [comment]
Recast doesn't appear to be working, I'm currently investigating.

**Comment by whikloj** [comment]
Popping in to say that Recast is (to my knowledge) not being used anywhere. It was developed to provide a way generate  Fedora URIs for things that are Drupal links. It used to look them up in Gemini and now just uses the internal UUID generator that @dannylamb made. 

We never figured out a good way to cause the RDF in Fedora to get run through this tool and updated to include these new triples.

All that is to say, this does not need to be a high priority.

**Comment by nigelgbanks** [comment]
@dannylamb should I remove the recast image then? No point in building it if we aint gonna use it.

**Comment by dannylamb** [comment]
Go right ahead.  If we have @whikloj 's blessing then burn it. :fire: :fire: :fire:

**Comment by g7morris** [comment]
@nigelgbanks Are you going to remove the recast image or does @whikloj need to say a few nice words before we set recast's funeral pyre off?

**Comment by nigelgbanks** [comment]
If @dannylamb is fine with axing it I'll just remove it seeing as we've not actually used it for well years... :smile:

**Comment by nigelgbanks** [comment]
Since this is removing an image though, we'll push it off to the 2.0 release

**Comment by nigelgbanks** [comment]
Done under https://github.com/Islandora-Devops/isle-buildkit/pull/238
