### ISSUE TITLE
ALPACA_FCREPO_URL validation of configured setting?

### ISSUE THREAD

**Issue by misilot** [Islandora-Devops/isle-buildkit#221]
Should this value `ALPACA_FCREPO_URL=http://fcrepo/fcrepo/rest` located at https://github.com/Islandora-Devops/isle-buildkit/blob/main/alpaca/Dockerfile#L50. Should this be `ALPACA_FCREPO_URL=http://fcrepo:8080/fcrepo/rest` if so I can make a PR for it.

**Comment by nigelgbanks** [comment]
@misilot good catch you are correct
