### ISSUE TITLE
HYPERCUBE_FCREPO_URL needs updating maybe?

### ISSUE THREAD

**Issue by misilot** [Islandora-Devops/isle-buildkit#224]
aoelschlager on [slack](https://islandora.slack.com/archives/CM6F4C4VA/p1652912611125699) pointed out https://github.com/Islandora-Devops/isle-buildkit/blob/main/hypercube/Dockerfile#L33

@dannylamb or @nigelgbanks do you know if this needs to change to :8080 and possibly have http:// prepended to it? 

These microservices are a blackbox to me, so not really sure.

**Comment by nigelgbanks** [comment]
Looks to be dead code:

Remove:

- https://github.com/Islandora-Devops/isle-buildkit/blob/main/hypercube/rootfs/etc/confd/templates/config.yaml.tmpl#L6-L7
- https://github.com/Islandora-Devops/isle-buildkit/blob/829ba4498ae0d0d699e3b44c88d48e282b3d71b6/hypercube/Dockerfile#L33
- https://github.com/Islandora-Devops/isle-buildkit/blame/main/hypercube/README.md#L15

**Comment by nigelgbanks** [comment]
While in there update the docs for milliner `MILLINER_FCREPO_URL` in the readme doesn't match the `Dockerfile`.

**Comment by g7morris** [comment]
@nigelgbanks Roger that. Testing this now https://github.com/Islandora-Devops/isle-buildkit/pull/241

**Comment by g7morris** [comment]
Updated and tested. Merge when ready

**Comment by nigelgbanks** [comment]
Merged
