### ISSUE TITLE
One jar to rule them all

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#225]
Replace Karaf with the one jar to rule them all, and in the micro services bind them.

**Comment by g7morris** [comment]
@nigelgbanks Do you want to schedule a Zoom call re this task or talk in Slack sometime this week to divvy up next steps between the two of us?

**Comment by g7morris** [comment]
@nigelgbanks Did you still want to consider this part of the non-breaking Oct release or should I move this issue somewhere else?

**Comment by nigelgbanks** [comment]
Ya we'll do it in the oct release I'll dig into it today, and some of these older tickets.

**Comment by nigelgbanks** [comment]
Turns out the change required removing environment vars since that kinda changes the contract with consumers of the image I'm gonna push it to the 2.0 release (I'm in the process of testing it though now),

**Comment by nigelgbanks** [comment]
Done under https://github.com/Islandora-Devops/isle-buildkit/pull/238
