### ISSUE TITLE
*.localhost domains on OSX

### ISSUE THREAD

**Issue by jonathangreen** [Islandora-Devops/isle-buildkit#23]
This doesn't seem to be a problem in Linux, and I don't have a windows box to test, but on OSX it seems like all the `*.localhost` domains we use for ISLE don't resolve automatically. 

They do resolve in Chrome because Chrome seems to resolve all *.localhost domains without going to the system resolver, but [firefox doesn't do this](https://bugzilla.mozilla.org/show_bug.cgi?id=1433933), and system utilities don't do this (`ping`, `host`, etc). 

Should we add a section to the readme? It could say to add something like this to your `/etc/hosts` if you are on OSX and not using Chrome:
```
# ISLE v8 domains
127.0.0.1     activemq.localhost
127.0.0.1     blazegraph.localhost
127.0.0.1     drupal.localhost
127.0.0.1     fcrepo.localhost
127.0.0.1     matomo.localhost
```

I can make a PR for this if it sounds reasonable.

**Comment by jonathangreen** [comment]
You can also do something [like this with dnsmasq](https://gist.github.com/eloypnd/5efc3b590e7c738630fdcf0c10b68072) to get `*.localhost` to work on OSX as well, but something like suggesting the host file entries like above is probably easier to add to the README.

**Comment by nigelgbanks** [comment]
This is covered now under: https://github.com/Islandora-Devops/isle-dc/pull/83 in particular: https://github.com/Islandora-Devops/isle-dc/blob/5960d5b4ce5c15ed2a8c731069b2c7a2532ca9be/README.md#configuring-the-domains
