### ISSUE TITLE
Look into caching to folder

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#240]
Buildkit has likely improved its cache to a folder (rather than using registry image cache). Have a look into this might be able to improve the build times significantly?

**Comment by g7morris** [comment]
@nigelgbanks Do you want to schedule a Zoom call re this task or talk in Slack sometime this week to divvy up next steps between the two of us?

**Comment by nigelgbanks** [comment]
Explored and tested all  the caching options (`s3`, `gha`, `local`), etc and settled on https://docs.docker.com/build/cache/backends/registry/ as it works the best for both local and Github Action based builds.
