### ISSUE TITLE
Upgrade Solr

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#243]
Currently, Solr is using arguments for `ps` that are not supported by busybox (therefore also Alpine).

```
idc-solr-1        | [cont-init.d] 02-setup-environment.sh: exited 0.
idc-solr-1        | [cont-init.d] 02-solr-setup.sh: executing... 
idc-solr-1        | [cont-init.d] 02-solr-setup.sh: exited 0.
idc-solr-1        | [cont-init.d] done.
idc-solr-1        | [services.d] starting services
idc-solr-1        | [services.d] done.
idc-solr-1        | ps: unrecognized option: p
idc-solr-1        | BusyBox v1.33.1 () multi-call binary.
idc-solr-1        | 
idc-solr-1        | Usage: ps [-o COL1,COL2=HEADER] [-T]
idc-solr-1        | 
idc-solr-1        | Show list of processes
idc-solr-1        | 
idc-solr-1        | 	-o COL1,COL2=HEADER	Select columns for display
idc-solr-1        | 	-T			Show threads
idc-solr-1        | This script relies on a version of ps that supports the -p flag.
idc-solr-1        | 
idc-solr-1        | Please install a POSIX compliant version and try again.
idc-solr-1        | [cont-finish.d] executing container finish scripts...
idc-solr-1        | [cont-finish.d] done.
idc-solr-1        | [s6-finish] waiting for services.
idc-solr-1        | [s6-finish] sending all processes the TERM signal.
idc-solr-1        | [s6-finish] sending all processes the KILL signal and exiting.
idc-solr-1 exited with code 0
```

This has been resolved [here](https://issues.apache.org/jira/browse/SOLR-16191).

Upgrading to versions 8.11.2 and 9.1 or greater should resolve the issue.

~~It is a low-priority issue, as only a warning is printed. Since the process always starts from a clean slate, no existing process for `solr` should be present.~~

Doesn't seem to be an issue on our older version of `solr` presently, that being said, `solr` should be updated regardless.

**Comment by nigelgbanks** [comment]
This should wait until after https://github.com/Islandora-Devops/isle-buildkit/issues/215, as upgrading Solr will constitute a major release, as folks will need to update their Drupal site as well.

**Comment by DonRichards** [comment]
@nigelgbanks Is this not the issue causing my exit code?

**Comment by nigelgbanks** [comment]
@DonRichards  I can't actually replicate this on the 1.0.7 release, do you have a custom solr image?

**Comment by nigelgbanks** [comment]
My bad for not reading the whole log, I just assumed it was the same as the activemq issue.

**Comment by DonRichards** [comment]
Yes. We forked this a while back and I'm now playing catchup.

**Comment by nigelgbanks** [comment]
Oh I'd check your image then, quick fix might be to install the GNU version of `ps` i.e. `apk add procps` or changing your version of solr.
