### ISSUE TITLE
Update Crayfish to use 3.x

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-buildkit#249]
[Crayfish](https://github.com/Islandora/crayfish) has been rebuilt as Symfony and new development is going on the 3.x branch. One release has been created thus far, [3.0.0.](https://github.com/Islandora/Crayfish/releases/tag/3.0.0)

Buildkit seems to be pinning the Crayfish version to 2.0.0: https://github.com/Islandora-Devops/isle-buildkit/blob/main/crayfish/Dockerfile#L6-L12

**Comment by nigelgbanks** [comment]
Being done as part of https://github.com/Islandora-Devops/isle-buildkit/issues/215 as the PHP upgrade necessitated it.

**Comment by nigelgbanks** [comment]
Done under #238
