### ISSUE TITLE
solr java memory max/min variables

### ISSUE THREAD

**Issue by rbos** [Islandora-Devops/isle-buildkit#252]
solr on isle-dc is being invocated with java -server -Xms512m -Xmx512m - we're getting solr OOM errors when indexing our site. 

I'm told there's no variable in the docker files to change that. Can someone add one?

**Comment by nigelgbanks** [comment]
Good shout, I'll add it in.

**Comment by nigelgbanks** [comment]
@rbos Raised pull request for review here: https://github.com/Islandora-Devops/isle-buildkit/pull/253

**Comment by rbos** [comment]
\o/ thanks

**Comment by nigelgbanks** [comment]
Merged, we'll try to get 1.0.8 release tomorrow if possible if you can't wait that long you can use the commit hash `2da6c10030ef18d6a7507922e1efe799b189d3cd` instead of the tag `1.0.7` to get the image.

**Comment by rbos** [comment]
I updated to 1.0.8, set `SOLR_MEMORY=1024` in `.env`, did `make down; make up` but when I look at ps, it still seems to be set to 512m: `/usr/lib/jvm/default-jvm/bin/java -server -Xms512m -Xmx512m`

**Comment by nigelgbanks** [comment]
The `.env` file doesn't put environment variables into the environment of the containers. 

https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers

You'll need to update the docker compose YAML files to pass in environment variables for the container.

**Comment by rbos** [comment]
Oh, I think I got it. In the "main" docker-compose.yml in the isle-dc root, I modified the 'solr' section in there.

**Comment by nigelgbanks** [comment]
I've tested this locally:

```bash
docker run --rm -ti -e SOLR_MEMORY=1024m --name solr islandora/solr:1.0.8 
```

And in another terminal, I can confirm the memory value is being passed through:

```bash
docker exec -ti solr ps aux | grep java
  604 solr      0:02 /usr/lib/jvm/default-jvm/bin/java -server -Xms1024m
```

**Comment by nigelgbanks** [comment]
Oh good you have it sorted, I don't really use `isle-dc` and haven't kept up with it's development so I'm not 100% sure about how / where to make the change in it.
