### ISSUE TITLE
2.0.0 Release 

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#261]
Be sure to add required steps for rebuilding Solr index / exporting configuration instructions in the release notes.

See discussion here: https://github.com/Islandora-Devops/isle-buildkit/pull/244

**Comment by nigelgbanks** [comment]
Also need a set of steps for upgrading Matomo, as we are bumping to the next major version and it requires database changes.

**Comment by g7morris** [comment]
@nigelgbanks I think we've hit all the metrics for this. Closing this issue
