### ISSUE TITLE
Remove demo image for 2.0.0 release

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#262]
It's basically unmaintained and doesn't work with PHP 8.1, also we're pushing folks towards adopting the start site approach.

**Comment by edlington** [comment]
@nigelgbanks wondering what this means: "also we're pushing folks towards adopting the start site approach." Is that at the container level? Or at the composer level? Both?

**Comment by nigelgbanks** [comment]
I've built out a `test` image that uses the basic site and has some sample content in it. It's being used by buildkit to run automated tests on pull requests to ensure that derivative generation, etc. doesn't get broken. It could be potentially used.

**Comment by nigelgbanks** [comment]
Done under https://github.com/Islandora-Devops/isle-buildkit/pull/238 Includes a workflow that does this.
