### ISSUE TITLE
Remove FCREPO 5 image for 2.0 release?

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#263]
@dannylamb do we still need to support Fedora 5? 6 seems stable?

**Comment by dannylamb** [comment]
And we do have a way forward that I've played with.  Maybe it's a bit creaky at times, but I've managed to do it with small data sets no problem.

**Comment by nigelgbanks** [comment]
Done under https://github.com/Islandora-Devops/isle-buildkit/pull/238
