### ISSUE TITLE
Alpine fixed to specific version 3.15.0

### ISSUE THREAD

**Issue by misilot** [Islandora-Devops/isle-buildkit#264]
Alpine is fixed to the specific version 3.15.0 which was released back on 2021-11-24.

Would it make sense to use the tag 3.15 instead, so new releases are pulled in during the build process, or to better track the specific versions for more stability, which would be 3.15.6 (at the time of creating)

Just a heads up, that 3.16 removes PHP7, so probably can't use that version yet, https://www.alpinelinux.org/posts/Alpine-3.16.0-released.html

**Comment by nigelgbanks** [comment]
Closing as a duplicate: https://github.com/Islandora-Devops/isle-buildkit/issues/215 (I've been actively working on this ticket for the last 3 days)

**Comment by nigelgbanks** [comment]
You can see the progress here: https://github.com/Islandora-Devops/isle-buildkit/pull/238

Note I rebase often, it's not a safe branch to work from for the moment.
