### ISSUE TITLE
Upgrade PHP 7 to 8 due to new warnings in Drupal 9 about deprecated PHP

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#267]
As written on the tin: Please consider upgrading PHP 7 to 8 due to new warnings (as of 11/30/22) in Drupal 9 about deprecated PHP.

Here is an example screenshot from the Status Report of a site running ISLE-DC with Nginx `1.18.0`, Drupal `9.4.8` & PHP `7.4.26`

![Screenshot 2022-11-30 at 4 27 29 PM](https://user-images.githubusercontent.com/501554/205112759-807153b0-2185-43c8-8853-c240dee3bde6.png)

The current nginx service [Dockerfile](https://github.com/Islandora-Devops/isle-buildkit/blob/main/nginx/Dockerfile#L12) for the  indicates `php7` is in use. (_this is expected_)

---

I fully anticipate that we should possibly make this into a release / sprint of its own @nigelgbanks given the potential for breakage across all Drupal modules. 

We should also consider enlisting more testers etc e.g. maybe make it more formal? 

Feels like we could plan for a Jan / Feb release. 

Is this something we should bring to the weekly Islandora Tech meeting?

Would love your thoughts, ideas on this when you have a chance. Cheers!

**Comment by g7morris** [comment]
@misilot Understood but that ticket doesn't seem to be very specific about its intent. Additionally we don't know what breaking changes or impact an upgrade to PHP 8 will have on Drupal Modules. I'm recommending to @nigelgbanks to make it a more formal breaking release and to invite the community for a sprint and testing as an idea. 

Would that be something you're interested in helping with too?

**Comment by misilot** [comment]
I would be happy to do some testing, once I can get our custom codebase working on a new install.

**Comment by nigelgbanks** [comment]
Done under #238
