### ISSUE TITLE
Bump S6-Overlay when the following issues will be resolved in their next release.

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#269]
Issue: https://github.com/just-containers/s6-overlay/issues/503

Basically, our finish script checks to see if all the services exited gracefully when receiving a SIGTERM. If so, they exit 0, if not, they exit with 128+15=143, to indicate that the service exited due to an unhandled `SIGTERM` (15).  The issue above is where a service triggers the container to exit by calling halt after it has exited, in which case s6-overlay is not respecting `S6_SERVICES_GRACETIME` value and immediately calling `SIGKILL` on the remaining services rather than waiting for the grace time. 

This by and large only effects the JAVA services (ActiveMQ, Fcrepo, etc) which is fortunate in that they are typically the only service running in the container (so not affected by the bug), except when we are also running tests, as the tests are additional services.

**Comment by nigelgbanks** [comment]
Hmm, in the meanwhile I'll just update the tests to accept a list of exit codes (rather than a singular value), and we'll remove the acceptance of `143` later after the issue in s6-overlay is resolved.

**Comment by rosiel** [comment]
Is this still an issue?

**Comment by nigelgbanks** [comment]
Yup
