### ISSUE TITLE
Cannot build 'base' image, preventing other images from building.

### ISSUE THREAD

**Issue by dannylamb** [Islandora-Devops/isle-buildkit#272]
I'm using Docker 20.10.2.  I've tried using Java 8, 11, and 14 all unsuccessfully.  It will build a few images, but then it will get stuck on building `base` and won't go any further.  It'll just sit there and run forever without actually making any progress.

```
#15 exporting to image
#15 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#15 exporting layers done
#15 writing image sha256:fefcaafd23eb784049713e005f1eace37d0cfd44f4760ea7437fa0dab91ed225 done
#15 naming to docker.io/local/crayfish:latest done
#15 DONE 0.0s
<=======------> 58% EXECUTING [1m 13s]
> IDLE
> IDLE
> :base:build
```

This used to work for me as of a few months ago.  I'd like to build and test updating matomo, but am having a heck of a time getting it to build after I bump the version number and the sha for the download.

**Comment by nigelgbanks** [comment]
It wouldn't be able to build crayfish without first building `base`.  Likely has nothing to do with Java, perhaps `buildkit` is dying under heavy load (I've noticed that a few times myself) in which cases the process just hangs until it times out. 

https://github.com/Islandora-Devops/isle-buildkit/pull/238

Uses a different build system (which can fail in the same way) but subsequent runs generally work.
