### ISSUE TITLE
HTTPS_URCE typos

### ISSUE THREAD

**Issue by rbos** [Islandora-Devops/isle-buildkit#291]
Hi,
I think someone screwed up a search & replace somewhere. A bunch of Cantaloupe environment variables use

`HTTPS_URCE`

instead of

`HTTPSOURCE`.

**Comment by nigelgbanks** [comment]
Good catch a fix has been applied to main. https://github.com/Islandora-Devops/isle-buildkit/commit/ce8dd66b0023b2f80e3d5f50675849a6b3a83839
