### ISSUE TITLE
http cantaloupe middleware omitted

### ISSUE THREAD

**Issue by rbos** [Islandora-Devops/isle-buildkit#303]
As of 2.0.10 in `docker-compose.cantaloupe.yml`

`      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-cantaloupe_https.middlewares=cantaloupe`

should also include the HTTP middleware for completeness. This broke my (http-only) derivatives.

`      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-cantaloupe_http.middlewares=cantaloupe`

**Comment by nigelgbanks** [comment]
This seems to be an issue for the isle-dc repository? The included [docker-compose.yml](https://github.com/Islandora-Devops/isle-buildkit/blob/098aa3adac39bcf2c5d3b6a0b8d262c4cedb7eef/docker-compose.yml#L111) file in this repository is for local testing, and only supports `https`, all `http` traffic is redirected to `https`.
