### ISSUE TITLE
Expose conf file for mariadb

### ISSUE THREAD

**Issue by ajstanley** [Islandora-Devops/isle-buildkit#309]
Drupal's preference is to have the isolation level for transactions set to READ-COMMITTED instead of the default  REPEATABLE-READ.  If the config file were exposed and persistable we could change that default, and allow some performance tuning

**Comment by nigelgbanks** [comment]
Environment variables can be added like the existing ones. 

https://github.com/Islandora-Devops/isle-buildkit/tree/main/mariadb#settings
https://github.com/Islandora-Devops/isle-buildkit/blob/main/mariadb/rootfs/etc/confd/templates/mariadb-server.cnf.tmpl#L11

Alternatively, if you want to just provide your own file, you can mount it at `/etc/confd/templates/mariadb-server.cnf.tmpl` and that file will be used for `/etc/my.cnf.d/mariadb-server.cnf` when the template renders.
