### ISSUE TITLE
Upgrade to PHP 8.3

### ISSUE THREAD

**Issue by aOelschlager** [Islandora-Devops/isle-buildkit#329]
This would help to test [Islandora pr 1007](https://github.com/Islandora/islandora/pull/1007) and it is a requirement for [Drupal 11.](https://www.drupal.org/about/core/blog/drupal-110-will-require-php-83-and-mysql-80)

**Comment by nigelgbanks** [comment]
Updated leptonica and imagemagick. Some issue with mariadb / crayfish remain.

**Comment by nigelgbanks** [comment]
https://github.com/Islandora-Devops/isle-buildkit/pull/330

**Comment by nigelgbanks** [comment]
@aOelschlager It's ready for review / test at #330

**Comment by aOelschlager** [comment]
Thank you @nigelgbanks!
