### ISSUE TITLE
Update build instructions for OSX

### ISSUE THREAD

**Issue by joshdentremont** [Islandora-Devops/isle-buildkit#342]
Some of the instructions in the READMEs don't work on OSX. It would be nice if we could update them so they work for both OSX and Linux, or add new OSX instructions.

For example, I don't have wget on my machine, so when I want to generate a new SHA to update the version of something included in an image I need to modify the commands in the README. Instead of running `wget --quiet "${URL}"` I can run `curl "${URL}" -o "${FILE}"` which should work on Linux and OSX.

`make bake` also doesn't work for me, but `docker buildx bake` does.

I suspect there might be more, so it would be helpful to go through and test on OSX and Linux to make sure everything works as intended and update the docs accordingly.

**Comment by nigelgbanks** [comment]
https://github.com/Islandora-Devops/isle-buildkit?tab=readme-ov-file#requirements

The README specifies the need for using brew on OSX to install the GNU version of make, I think this brings `wget` in as well, though I'm not 100% sure. I'll merge a pull to update the README to change `wget` for `curl`.

**Comment by joecorall** [comment]
I think the only thing missing from the instructions for mac is needing to run this before `make bake`

```
docker context use default
```
