### ISSUE TITLE
Logging to stderr / stdout for all images / containers / services

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#36]
Logging to stderr / stdout for all images needs to be confirmed and fixed post-merge once everything is confirmed as working.

**Comment by g7morris** [comment]
Cross referenced here https://github.com/Islandora-Devops/isle-buildkit/pull/32

**Comment by nigelgbanks** [comment]
Resolved by https://github.com/Islandora-Devops/isle-buildkit/pull/32
