### ISSUE TITLE
Dockerhub - update all image information

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#37]
Create READMEs for all Dockerhub images with license information, links to Github Dockerfiles, tag information and image content

**Comment by dannylamb** [comment]
Is this possible given our setup with all the dockerfiles contained within one repo?  Pretty sure Dockerhub is expecting one Dockerfile / README per repository.

**Comment by nigelgbanks** [comment]
You can manually paste text into the description / read me via the DockerHub web UI, not sure if we can do it automatically to keep in sync.

**Comment by nigelgbanks** [comment]
This might be what we want: https://github.com/peter-evans/dockerhub-description

**Comment by dannylamb** [comment]
That looks like it could work

**Comment by nigelgbanks** [comment]
Tried the tool and there are two issues:

- There is a maximum character limit of 25,000 which we do exceed in some README files.
- Relative links to other documents break.

https://github.com/docker/hub-feedback/issues/238

**Comment by nigelgbanks** [comment]
Resolved by the following commits:

- 84e7770021bdaaa9a4e04c758c0af79986d19dcf
- 010b18cb23b21bb3bdf6eb9f4cbe2bde230e47a4
- fc5c56ceec044788946b4514733c197437a66631
