### ISSUE TITLE
Ensure proper licensing on all Dockerhub image READMEs & github repos e.g. MIT or GPL3

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#39]
Confer with @dannylamb for what is needed here

**Comment by nigelgbanks** [comment]
Everything in the repository is currently licensed as MIT:

https://github.com/Islandora-Devops/isle-buildkit/blob/main/LICENSE
https://github.com/Islandora-Devops/isle-buildkit/blob/main/base/Dockerfile#L45

The images themselves dunno how that works in practice as there is a tonnes of software bundled in them. I think we can close this, @g7morris?
