### ISSUE TITLE
Move traefik service setup into it's own docker-compose file

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#43]
From https://github.com/Islandora-Devops/isle-dc/pull/6

Comment from @nikathone 

"Also it might be a good idea to move the traefik service setup in it's own docker-compose file cause ideally they should only be one traefik service per local host."

We should discuss how to do this post-merge.

**Comment by nigelgbanks** [comment]
Might be tricky, I think traefik needs access to the bridge network(s) created by docker-compose to properly redirect the traffic, not sure if it's possible to do this. Might be able to "import" the network and set all of the containers in the docker-compose file to use the "imported" network, but then there wouldn't be any isolation, do the same as using the default network everywhere.

**Comment by nigelgbanks** [comment]
Looks like we can define the network explicitly, but only one: https://docs.traefik.io/providers/docker/#network

**Comment by nigelgbanks** [comment]
Found an example of the shared network approach: https://github.com/containous/traefik/issues/3599#issuecomment-405488436

**Comment by nigelgbanks** [comment]
Oh reading though the isle-dc repo I think I misunderstood the use case here. There would be two or more docker-compose.yml files in the same folder so they would run under the same network. Or was the intention for it to work across folders?

**Comment by nigelgbanks** [comment]
This is covered by https://github.com/Islandora-Devops/isle-dc/pull/83, now users can use a single `traefik` instance and spin up multiple environments, where can control traefik via `INCLUDE_TRAEFIK_SERVICE`
