### ISSUE TITLE
gradle.properties value needed

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Devops/isle-buildkit#53]
Just tried to build this on an EC2 Ubuntu server and got an error easily corrected within the repo.

<img width="1294" alt="Screen Shot 2020-06-18 at 7 48 06 AM" src="https://user-images.githubusercontent.com/2738244/85016622-15c8fd80-b138-11ea-9f70-68eeb7e8f03f.png">

## Fix
Run this to get your 
```shell
$ echo $JAVA_HOME

/usr/lib/jvm/default-java
```

Now place what returned from `$JAVA_HOME` in at the bottom of the **gradle.properties** file
```yml
   org.gradle.java.home=/usr/lib/jvm/default-java
```

I believe adding this in the repo as a pointer will speed up onboarding.

**Comment by nigelgbanks** [comment]
Unfortunately that path is specific to your machine, it would differ for those not using Ubuntu, or who install java via a different means on Ubuntu. Our goal is to support developers on OSX and Windows as well. What we could do is update the README.md with a FAQ that documents this.

**Comment by DonRichards** [comment]
Sounds good to me!
