### ISSUE TITLE
Add support for file mounted secrets for Docker Swarm / Kubernetes 

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#57]
<https://docs.docker.com/engine/swarm/secrets/>

This can be done by injecting some logic to check for the presence of a secrets mounted file and to prefer it's contents to what confd provides.

In the setup environment templates  https://github.com/Islandora-Devops/isle-buildkit/blob/master/drupal/rootfs/etc/confd/templates/drupal-setup-environment.sh.tmpl

**Comment by dannylamb** [comment]
We're doing this now.  Secrets are mounted in and then read into environment variables.
