### ISSUE TITLE
Remove all execline configuration scripts

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#89]
Its confusing best replace it with bash, and make the defaults more discover able and less 'scripty'.

**Comment by nigelgbanks** [comment]
This will probably also get covered as the system around confd is being overhauled https://github.com/Islandora-Devops/isle-dc/issues/119

**Comment by nigelgbanks** [comment]
wip: https://github.com/nigelgbanks/isle-buildkit/tree/bye-bye-execline

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/isle-buildkit/commit/25a016543cc324980f53e071120c39904b7619a1
