### ISSUE TITLE
Fedora - Add support for multiple backends to fedora

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-buildkit#9]
_Originally from the https://github.com/Islandora-Devops/isle-buildkit/README.md_

* Add support for multiple backends to fedora (currently only file is being used)

* This functionality to toggle between backends (file, mysql and postgres) already exists in [isle-dc](https://github.com/Islandora-Devops/isle-dc/blob/development/fcrepo.env#L34) & within the [isle-fcrepo image](https://github.com/Islandora-Devops/isle-fcrepo/blob/dev/rootfs/opt/fcrepo/config/fcrepo-config.xml#L42) as a feature which should be ported to `isle-buildkit`.

* Is Fedora configured to use [Blazegraph](https://github.com/Islandora-Devops/isle-buildkit/issues/7)?

**Comment by nigelgbanks** [comment]
I'm taking a look at this now as I'm trying to get s3 working.

**Comment by dannylamb** [comment]
We now support mysql and postgresql.  With Fedora 6 those are the only two options (other than the embedded h2 for testing purposes), so we're good to close this one.
