### ISSUE TITLE
Fix tagging

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-buildkit#90]

**Comment by nigelgbanks** [comment]
Make it happen automatically via Github actions remove default publish of 0.01

**Comment by nigelgbanks** [comment]
Still up for discussion. #119 will resolve the issue where it is impossible **to not** tag a build as latest. Releases currently take the git tag name (i.e. 0.0.1), all others use the commit hash. There is no per branch tags like main, or main-stable, etc. Though we could add it.

Tagging @dannylamb, @noahwsmith as this has been discussed before, do we want to add some more logic to this?

**Comment by dannylamb** [comment]
That sounds right to me @noahwsmith and @nigelgbanks
